title: tobias dalberg
author: tobias dalberg
twitter_username: tobias_dalberg
github_username: tdalberg
theme: minima

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - cv.md
 - writings.md
 - presentations.md

# SEO
google_site_verification : "rNVpT0EGDErzM_rNLzSVl2yFWvL04B4lRHQ7wlMNpQU"

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - jemoji

mapping:
 provider: openstreetmap
 zoom: 8
 dimensions:
  width: 600
  height: 400