title: tobias dalberg
author: tobias dalberg
github_username: tdalberg
theme: minima

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - cv.md
 - writings.md

# SEO
google_site_verification : "rNVpT0EGDErzM_rNLzSVl2yFWvL04B4lRHQ7wlMNpQU"

gems:
 - jekyll-seo-tag
 - jekyll-sitemap
